### ISSUE TITLE
Grouped Convolutions

### ISSUE THREAD

**Issue by liaopeiyuan** [uwplse/tensat#4]
Dear Authors,

I was reading the implementation for ResNeXt-50 and noticed that the `groups` argument is not passed in: https://github.com/uwplse/tensat/blob/704e1bdf105bd26d766dc2f7d6b64fa5f36f632e/src/resnext50.rs#L18 How does the backend (TASO) know that a convolution is a grouped one?

**Comment by yycdavid** [comment]
TASO's backend automatically infers if the convolution is a grouped one by checking the shapes of the input and weight tensors. See: https://github.com/jiazhihao/TASO/blob/master/examples/resnext50.py for the example resnext in TASO.

**Comment by liaopeiyuan** [comment]
Got it, thanks!

**Comment by liaopeiyuan** [comment]
Another quick question: is the ONNX backend aware of this?

**Comment by remysucre** [comment]
ONNX goes through TASO, so it might work. Would it be easy to try?

**Comment by liaopeiyuan** [comment]
Yes, I confirm that group size is included in TASO.

**Comment by remysucre** [comment]
Thanks.
